name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and tag Docker image
        run: docker build --tag ghcr.io/${{ github.repository }}:latest .

      - name: Authenticate with ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Publish Docker image to ghcr
        run: docker push ghcr.io/${{ github.repository }}:latest
